# Generated by Django 5.0.6 on 2024-06-12 19:29

import django.db.models.deletion
import django.utils.timezone
import homepage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Miniature_Image', models.ImageField(blank=True, null=True, upload_to=homepage.models.Item.uploadDirectoryPath)),
                ('Upload_Date', models.DateField(default=django.utils.timezone.now)),
                ('approve_status', models.IntegerField(default=0)),
                ('Media', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='homepage.author')),
                ('Uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approve_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('approve_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('approve_status', models.IntegerField(default=0)),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=homepage.models.Item_Image.uploadDirectoryPath, verbose_name='Attachment')),
                ('View_Detail', models.CharField(default='Null', max_length=75)),
                ('Index', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.item')),
            ],
        ),
        migrations.CreateModel(
            name='RTI_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Has_DZI', models.BooleanField(default=False)),
                ('Has_TZI', models.BooleanField(default=False)),
                ('Has_Image', models.BooleanField(default=False)),
                ('Info_File', models.FileField(upload_to='')),
                ('RTI_Zip', models.FileField(default=None, null=True, upload_to=homepage.models.RTI_File.uploadDirectoryPath)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti', to='homepage.item')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('RTI_File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='homepage.rti_file')),
            ],
        ),
    ]
