# Generated by Django 5.0.6 on 2024-06-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
