# Generated by Django 5.0.6 on 2024-06-24 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_item_accession_number_item_alternate_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='approve_record',
            old_name='approve_status',
            new_name='Approval_Status',
        ),
        migrations.RemoveField(
            model_name='approve_record',
            name='approve_time',
        ),
        migrations.RemoveField(
            model_name='approve_record',
            name='item',
        ),
        migrations.RemoveField(
            model_name='approve_record',
            name='upload_time',
        ),
        migrations.RemoveField(
            model_name='approve_record',
            name='upload_user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='item',
            name='comment',
        ),
        migrations.AddField(
            model_name='approve_record',
            name='Approval_Admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Approval', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approve_record',
            name='Approval_Comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approve_record',
            name='Approval_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='approve_record',
            name='Approval_File',
            field=models.FileField(blank=True, null=True, upload_to='approval_files/'),
        ),
        migrations.AddField(
            model_name='item',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Photographer',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approve_record',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Approval', to='homepage.item'),
            preserve_default=False,
        ),
    ]
