# Generated by Django 5.0.6 on 2024-06-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_approve_status_approve_record_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Photographer',
        ),
        migrations.AddField(
            model_name='item',
            name='Author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='homepage.author'),
            preserve_default=False,
        ),
    ]
