# Generated by Django 5.0.6 on 2024-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_item_email_remove_item_photographer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Author',
        ),
        migrations.AddField(
            model_name='item',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Photographer',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
