# Generated by Django 5.0.6 on 2024-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_item_author_item_email_item_photographer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Photographer',
        ),
        migrations.AddField(
            model_name='item',
            name='Author',
            field=models.ManyToManyField(related_name='items', to='homepage.author'),
        ),
    ]
