# Generated by Django 5.0.6 on 2024-07-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_item_email_remove_item_photographer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Email',
        ),
        migrations.AlterField(
            model_name='item',
            name='Bibliography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
